/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Midbox_CONSTANTS_H
#define Midbox_CONSTANTS_H

#include "Midbox_types.h"

namespace mb {

class MidboxConstants {
 public:
  MidboxConstants();

};

extern const MidboxConstants g_Midbox_constants;

} // namespace

#endif
