/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Midbox_constants.h"

namespace mb {

const MidboxConstants g_Midbox_constants;

MidboxConstants::MidboxConstants() {
}

} // namespace

