/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Midbox_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace mb {


TQueryKey::~TQueryKey() throw() {
}


void TQueryKey::__set_Trapdoor(const std::string& val) {
  this->Trapdoor = val;
}

void TQueryKey::__set_Mask(const std::string& val) {
  this->Mask = val;
}

const char* TQueryKey::ascii_fingerprint = "07A9615F837F7D0A952B595DD3020972";
const uint8_t TQueryKey::binary_fingerprint[16] = {0x07,0xA9,0x61,0x5F,0x83,0x7F,0x7D,0x0A,0x95,0x2B,0x59,0x5D,0xD3,0x02,0x09,0x72};

uint32_t TQueryKey::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_Trapdoor = false;
  bool isset_Mask = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->Trapdoor);
          isset_Trapdoor = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->Mask);
          isset_Mask = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_Trapdoor)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_Mask)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TQueryKey::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("TQueryKey");

  xfer += oprot->writeFieldBegin("Trapdoor", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->Trapdoor);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("Mask", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->Mask);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(TQueryKey &a, TQueryKey &b) {
  using ::std::swap;
  swap(a.Trapdoor, b.Trapdoor);
  swap(a.Mask, b.Mask);
}

TQueryKey::TQueryKey(const TQueryKey& other0) {
  Trapdoor = other0.Trapdoor;
  Mask = other0.Mask;
}
TQueryKey& TQueryKey::operator=(const TQueryKey& other1) {
  Trapdoor = other1.Trapdoor;
  Mask = other1.Mask;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const TQueryKey& obj) {
  using apache::thrift::to_string;
  out << "TQueryKey(";
  out << "Trapdoor=" << to_string(obj.Trapdoor);
  out << ", " << "Mask=" << to_string(obj.Mask);
  out << ")";
  return out;
}

} // namespace
